name: RunTests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      grep:
        description: 'tests to grep'
        required: false
        default: ''
      run:
        required: false
      testomatio:
        required: false

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: rake test

      - name: Testomatio Report
        run: npx @testomatio/reporter xml "test/reports/**.xml" --lang=Ruby
        if: always()
        env:
          TESTOMATIO: ${{ secrets.TESTOMATIO }}
          TESTOMATIO_TITLE: "PR ${{ github.event.number }} ${{ github.event.pull_request.title }}"
          GH_PAT: ${{ github.token }}
          DEBUG: 1

